precio1 = int(input("precio del articulo: "))
precio2 = int(input("precio del articulo: "))
precio3 = int(input("precio del articulo: "))
titulo1 = ("el subtotal es: ")
titulo2 = ("el total es: ")
sub = (precio1 + precio2 + precio3)
total = sub * (1.16)
print(titulo1, sub)
print(titulo2, total)
